### ISSUE TITLE
Add support for resuming interrupted uploads

### ISSUE THREAD

**Issue by bhstahl** [stephenplusplus/gcs-resumable-upload#11]
The JSON api supports [resuming an interrupted upload](https://cloud.google.com/storage/docs/json_api/v1/how-tos/resumable-upload#resume-upload). It would be great to extend this library to support uploading file chunks that aren't the full file size. 

The `Content-Range` header can be constructed to allow smaller file chunks:

```javascript

  // Default to 0, the start byte, if offset isn't provided
  cfg.offset = parseInt(cfg.offset, 10);
  this.offset = isNaN(cfg.offset) ? 0 : cfg.offset;
 
  // Default to * if chunkSize isn't provided
  cfg.chunkSize = parseInt(cfg.chunkSize, 10);
  this.chunkSize = isNaN(cfg.chunkSize) ? '*' : cfg.chunkSize;

  // Default to * if entire file size isn't provided
  var contentLength = 'contentLength' in cfg.metadata ? parseInt(cfg.metadata.contentLength, 10) : false;
  this.contentLength = isNaN(contentLength) ? '*' : contentLength;

  var reqOpts = {
    method: 'PUT',
    uri: this.uri,
    headers: {
      'Content-Range': 'bytes ' + this.offset + '-' + this.chunkSize + '/' + this.contentLength
    }
  }
```

I'm happy to take a stab at it if you're cool with this strategy, and if this is the best route to get support into [gcloud-node](https://github.com/GoogleCloudPlatform/gcloud-node).

**Comment by stephenplusplus** [comment]
I think this already supports resuming interrupted uploads: https://github.com/stephenplusplus/gcs-resumable-upload/blob/master/test.js#L98

I believe the API tracks how much data it has received, even without specific chunking intervals. Has this not been working for you in your testing?

**Comment by bhstahl** [comment]
Sorry, I should have clarified manually resuming interrupted uploads. For example, creating an upload, stopping/pausing for various reasons (but keeping track of the bytes left off), then resuming. Potentially even on an entirely different machine, without the convenience of a shared [ConfigStore](http://gitnpm.com/configstore). In my tests, this would override the bytes already uploaded to the GCS object, re-starting the offset at 0.

An example being the [GCSDataStore](https://github.com/tus/tus-node-server/blob/master/lib/stores/GCSDataStore.js) of [tus-node-server](https://github.com/tus/tus-node-server#resumable-upload) (my intended usage), or more simply:


 One file `single.mov`, split into two chunks, `split_aa` & `split_ab`
```bash
$ ls -ln
-rw-r--r--@ 1 501  20    1072201 May  8 08:23 single.mov
-rw-r--r--  1 501  20     572201 May  8 08:39 split_aa
-rw-r--r--  1 501  20     500000 May  8 08:39 split_ab
```

Uploaded to the same GCS object `single.mov`, resuming the upload with `split_ab` where `split_aa` left off
```javascript
// First chunk
fs.createReadStream('split_aa')
  .pipe(upload({ 
    file: 'single.mov',
    offset: 0,
  }))

// Second chunk later, or even possibly on a different server through a load balancer
fs.createReadStream('split_aa')
  .pipe(upload({ 
    file: 'single.mov',
    offset: 572202,
  }))
```

**Comment by stephenplusplus** [comment]
Gotcha, a PR would be awesome! Thanks for helping!
