### ISSUE TITLE
generation == 0 not respected

### ISSUE THREAD

**Issue by thromer** [stephenplusplus/gcs-resumable-upload#20]
The fix is easy, but I'm not familiar enough with the code base or javascript to be able to easily add a test case.

In Upload, change

  if (this.generation) {
    reqOpts.qs.ifGenerationMatch = this.generation
  }

to

  if (is.defined(this.generation)) {
    reqOpts.qs.ifGenerationMatch = this.generation
  }

**Comment by stephenplusplus** [comment]
Thank you. This was intentional. At the time of development, research showed 0 wasn't a possible value. Has that changed?

**Comment by thromer** [comment]
Yes, by setting if-generation-match = 0 on upload, the upload will fail if
the object already exists. Handy for locking.

The explanation here is pretty good:
https://cloud.google.com/storage/docs/object-versioning#_OverwritingObject

**Comment by stephenplusplus** [comment]
Thank you, I will get to this ASAP.

**Comment by stephenplusplus** [comment]
Thanks again -- fixed in the `0.7.7` release.

**Comment by thromer** [comment]
Thanks!
