### ISSUE TITLE
Enable renovate on this repo

### ISSUE THREAD

**Issue by ofrobots** [stephenplusplus/gcs-resumable-upload#25]
@stephenplusplus Can you enable greenkeeper.io on this repo?

**Comment by stephenplusplus** [comment]
After months and no support from Greenkeeper, I literally cannot :)

But that's okay, because renovate seems even better 👍

**Comment by JustinBeckwith** [comment]
*gentle ping* @stephenplusplus if you have a few minutes today - it would be rad if you could turn renovate on for this repo :)

**Comment by JustinBeckwith** [comment]
Thank you sir!
