### ISSUE TITLE
Error when calling createURI

### ISSUE THREAD

**Issue by winduptoy** [stephenplusplus/gcs-resumable-upload#3]
When I call `createURI`, I get the following error in my callback. It's pretty cryptic and I have no idea what's causing it.

```
	upload.createURI({
		bucket: 'mybucket',
		file: 'myfile.jpg',
		authConfig: {
			projectId: 'XXXXXX',
			keyFilename: 'XXXXXX'
		}
	}, function(err, uri) {
		console.log(err, uri);
	});
```

```
{ errors: [ { domain: 'global', reason: 'required', message: 'Required' } ],
  code: 400,
  message: 'Required' }
```

**Comment by stephenplusplus** [comment]
That's not fun at all. According to these docs: https://cloud.google.com/storage/docs/json_api/v1/status-codes that means somewhere along the way we made a "bad request". I'll jump on a computer later and try to reproduce. If you're up for some console.logging in the mean time, feel free :)

**Comment by stephenplusplus** [comment]
Would you put a `console.log(resp.toJSON())` [at this line](https://github.com/stephenplusplus/gcs-resumable-upload/blob/13bead5c52f6a2e9be7e94d3289d71ea95018111/index.js#L89) and paste the output?

**Comment by winduptoy** [comment]
`TypeError: Cannot read property 'toJSON' of undefined` (`resp` is undefined).

I get the same thing when I `console.log(JSON.stringify(body));` on [line 210](https://github.com/stephenplusplus/gcs-resumable-upload/blob/13bead5c52f6a2e9be7e94d3289d71ea95018111/index.js#L210) and the `resp` object there is a little too big to paste.

**Comment by stephenplusplus** [comment]
Woops, sorry for sending you down that road that was clearly wrong. Instead of logging `resp`, `resp.toJSON()` should produce a much more copy-pastable object.

**Comment by winduptoy** [comment]
Could this be the solution? I've created a bucket with a service account, and I'm trying to access it with that same service account, but do I need to give that service account write permissions? http://stackoverflow.com/a/17978592

I've removed what I believe to be potentially sensitive info, hope I didn't screw anything up.

```
{ statusCode: 400,
  body: { error: { errors: [Object], code: 400, message: 'Required' } },
  headers: 
   { 'x-guploader-uploadid': 'XXXXXX',
     vary: 'Origin, X-Origin',
     'content-type': 'application/json; charset=UTF-8',
     'content-length': '163',
     date: 'Wed, 02 Sep 2015 23:25:46 GMT',
     server: 'UploadServer',
     'alternate-protocol': '443:quic,p=1',
     'alt-svc': 'quic=":443"; p="1"; ma=604800',
     connection: 'close' },
  request: 
   { uri: 
      { protocol: 'https:',
        slashes: true,
        auth: null,
        host: 'www.googleapis.com',
        port: null,
        hostname: 'www.googleapis.com',
        hash: null,
        search: '?name%5B_bsontype%5D=ObjectID&name%5Bid%5D=U%C3%A7%C2%85ze%C3%98%C3%A232%22%02%C2%A3&uploadType=resumable',
        query: 'name%5B_bsontype%5D=ObjectID&name%5Bid%5D=U%C3%A7%C2%85ze%C3%98%C3%A232%22%02%C2%A3&uploadType=resumable',
        pathname: '/upload/storage/v1/b/thebucket/o',
        path: '/upload/storage/v1/b/thebucket/o?name%5B_bsontype%5D=ObjectID&name%5Bid%5D=U%C3%A7%C2%85ze%C3%98%C3%A232%22%02%C2%A3&uploadType=resumable',
        href: 'https://www.googleapis.com/upload/storage/v1/b/thebucket/o?name%5B_bsontype%5D=ObjectID&name%5Bid%5D=U%C3%A7%C2%85ze%C3%98%C3%A232%22%02%C2%A3&uploadType=resumable' },
     method: 'POST',
     headers: 
      { Authorization: 'Bearer XXXXXXX',
        accept: 'application/json',
        'content-type': 'application/json',
        'content-length': 2 } } }
```

**Comment by stephenplusplus** [comment]
I think the problem might be the filename:

```
name%5B_bsontype%5D=ObjectID&name%5Bid%5D=U%C3%A7%C2%85ze%C3%98%C3%A232%22%02%C2%A3&uploadType=resumable
```

Translated:
```
name[_bsontype]=ObjectID&name[id]=UçzeØâ32"£&uploadType=resumable"
```

Looks like maybe you're giving an object as the `file` property instead of a string?

**Comment by winduptoy** [comment]
OOOPS! You're totally right. Forgot a simple `.toString()`. Sorry for the headache. :dizzy_face:

**Comment by stephenplusplus** [comment]
No problem, glad we got it solved! :)
