### ISSUE TITLE
Time for a release!

### ISSUE THREAD

**Issue by JustinBeckwith** [stephenplusplus/gcs-resumable-upload#41]
So I've been monkeying around in here quite a bit.  I'd love to do a few smoke tests, and then get a release out there before I start doing even worse things.  

Are there a set of libraries / tests I should check out before we cut a new release? 

@stephenplusplus @ofrobots

**Comment by stephenplusplus** [comment]
Sounds good 👍 Definitely link it up to `@google-cloud/storage` and run the system tests, as that's where we're using this thing.

**Comment by JustinBeckwith** [comment]
I did an `npm link gcs-resumable` upload with what's in master right now, and the only two tests that failed were the ones we chatted about:

![image](https://user-images.githubusercontent.com/534619/38642365-b158a5b8-3d8e-11e8-9fd3-9446e39293b2.png)

Idea.  Would you mind taking what's in master, and releasing a release candidate package publish?  After that, we can update the package.json in storage to use it, and run it through the full circleCI being 120% sure we're not breaking anything.

Thoughts?

**Comment by stephenplusplus** [comment]
Welp, over on nodejs-storage, system tests don't run until they hit master. I think we can just go for it 👍 Let's try an 0.10.0!

**Comment by stephenplusplus** [comment]
0.10.0 is out.
