### ISSUE TITLE
configstore caused uploads to fail

### ISSUE THREAD

**Issue by richardkazuomiller** [stephenplusplus/gcs-resumable-upload#9]
Unfortunately I don't have any useful logs or error messages, but when using gcs-resumable-upload by way of gcloud-node I kept getting a "Not found" error when running as one user, but not as another user on the same machine. Without fully understanding what configstore is there for, I went ahead and deleted the `~/.config/configstore/gcs-resumable-upload.json` file, and suddenly uploads started working again! I wish I had looked at the contents of the configstore file before I did it, but my guess is that some invalid config was saved and needed to be rejiggered for anything with gcs-resumable-upload to work. 

I think it would be good if there was some sanity check before doing anything with the contents of that file. I have a cron job running every minute overwriting the same file over and over again, so there was probably some old invalid data in configstore that kept getting reused over and over because the job always uses the same filename.

**Comment by richardkazuomiller** [comment]
I briefly looked through the code and it looks like `deleteConfig` is only called after the `complete` event is fired. My hypothesis is that due to some error when initially making the request to GCS, the upload is never started and therefore the `compete` event is never fired, which means whatever weird state ConfigStore was in never gets reset. How the bad config got there in the first place is a mystery, but I think it could have been the process being killed in the middle of an upload or network issues or something like that. Is this possible?

**Comment by stephenplusplus** [comment]
Thanks for reporting this! I sent a PR that hopefully will address these scenarios: #10
